tools:
  exceptions: https://55ab055ee588476e8f906d0a3167a3ad@o358880.ingest.sentry.io/4504765277143040
  logging: https://service.us2.sumologic.com/ui/?appName=klear
  ci: https://github.com/dcsil/klear-backend/actions

services:
  production: https://github.com/dcsil/klear-backend

docs:
  getting_started: https://github.com/dcsil/klear-backend

commands:
  bootstrap: ./script/bootstrap
  database: bin/rails db:create db:migrate
  server: npm start
  test: npm npm run test